trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo Installing Flutter...
      sudo snap install flutter --classic
      flutter doctor
    displayName: 'Install Flutter'

  - script: |
      echo Installing dependencies and running Flutter tests...
      cd Frontend  # Update this if your Flutter project is in a different subdirectory
      flutter pub get
      flutter test
    displayName: 'Build and test Flutter app'
    continueOnError: true

  - script: |
      echo Setting up Node.js environment...
      curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
    displayName: 'Install Node.js'

  - script: |
      echo Building and testing React dashboard...
      cd Frontend  # Update this path if your React project is in a specific subdirectory
      npm install
      npm run build
      npm test
    displayName: 'Build and test React Dashboard'
    continueOnError: true

  - script: |
      echo Setting up Java environment...
      sudo apt-get install openjdk-11-jdk
    displayName: 'Install JDK'

  - script: |
      echo Building and testing Spring Boot application...
      cd Backend  # Update this path if your Spring Boot project is in a specific subdirectory
      ./mvnw clean install
    displayName: 'Build and test Spring Boot app'
    continueOnError: true

  - checkout: none
    displayName: 'Disable further repository syncing'

  - script: |
      echo All builds and tests are completed.
    displayName: 'Final Step'
