trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Flutter...
    cd Frontend/user/appUser
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Checking for pubspec.yaml...
    cd Frontend/user/appUser
    if [ ! -f pubspec.yaml ]; then
      $(which flutter) create .
    fi
  displayName: 'Check and create pubspec.yaml'

- script: |
    echo Installing dependencies...
    cd Frontend/user/appUser
    $(which flutter) pub get
  displayName: 'Install Flutter dependencies'

- script: |
    echo Analyzing Flutter app...
    cd Frontend/user/appUser
    $(which flutter) analyze
  displayName: 'Analyze Flutter app'

- script: |
    echo Running Flutter tests...
    cd Frontend/user/appUser
    $(which flutter) test
  displayName: 'Run Flutter tests'

- script: |
    echo Building Flutter app for the web...
    cd Frontend/user/appUser
    $(which flutter) build web
  displayName: 'Build Flutter app for the web'

- script: |
    echo Running Flutter app...
    cd Frontend/user/appUser
    $(which flutter) run -d chrome
  displayName: 'Run Flutter app as web server'
