trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Flutter...
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Checking for pubspec.yaml...
    if [ ! -f pubspec.yaml ]; then
      flutter create .
    fi
  displayName: 'Check and create pubspec.yaml'

- script: |
    echo Installing dependencies...
    flutter pub get
  displayName: 'Install Flutter dependencies'

- script: |
    echo Building Flutter app...
    flutter build apk --release
  displayName: 'Build Flutter app'

- script: |
    echo Running Flutter tests...
    flutter test
  displayName: 'Run Flutter tests'

- script: |
    echo Running Flutter app...
    flutter run
  displayName: 'Run Flutter app'
