trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Flutter...
    cd ecommerce-boutique/Frontend/user/appUser
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'
