trigger:
- main

pool:
  name: 'Continuous delivery - agent'
  demands:
  - agent.name -equals DESKTOP-SRQJNM7

variables:
  buildConfigPath: 'src/main/resources/application.properties'
  artifactName: '$(Build.BuildId)-$(Build.DefinitionName).jar'
  targetDirectory: 'C:\Users\hp\OneDrive\Desktop\ecom\FlutterEcommerce\Backend\ecomshop\target'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self

    - script: |
        mvn verify
      displayName: 'Build and test the application'
      workingDirectory: $(Build.SourcesDirectory)

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
        testRunTitle: 'Publish Test Results'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy JAR file to artifact staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - script: |
              echo "Deploying to $(environment.name)"
            displayName: 'Deploy Application'
