trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Cleaning directory...
    /snap/bin/flutter clean
  displayName: 'Clean directory'

- script: |
    echo Installing Flutter...
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Checking for pubspec.yaml...
    if [ ! -f pubspec.yaml ]; then
      /snap/bin/flutter create .
    fi
  displayName: 'Check and create pubspec.yaml'

- script: |
    echo Installing dependencies...
    /snap/bin/flutter pub get
  displayName: 'Install Flutter dependencies'
