trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Flutter...
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Checking for pubspec.yaml...
    if [ ! -f pubspec.yaml ]; then
      $(which flutter) create .
    fi
  displayName: 'Check and create pubspec.yaml'

- script: |
    echo Installing dependencies...
    $(which flutter) pub get
  displayName: 'Install Flutter dependencies'

- script: |
    echo Building Flutter app for the web...
    $(which flutter) build web
  displayName: 'Build Flutter app for the web'

- script: |
    echo Running Flutter app in Chrome...
    google-chrome-stable --app=http://localhost:5000
  displayName: 'Run Flutter app in Chrome'
  continueOnError: true

- checkout: none
  displayName: 'Disable further repository syncing'

- script: |
    echo All frontend builds and tests are completed.
  displayName: 'Final Step'
