trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Flutter...
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Creating pubspec.yaml...
    rm -f pubspec.yaml
    cd Frontend/user/appUser
    flutter create .
  displayName: 'Create pubspec.yaml'

- script: |
    echo Installing dependencies...
    cd Frontend/user/appUser
    flutter pub get
  displayName: 'Install Flutter dependencies'

- script: |
    echo Building Flutter app...
    cd Frontend/user/appUser
    flutter clean
    flutter build web --release
  displayName: 'Build Flutter app'

- script: |
    echo Running Flutter app in Chrome...
    cd Frontend/user/appUser
    flutter run -d chrome --release
  displayName: 'Run Flutter app in Chrome'

- checkout: none
  displayName: 'Disable further repository syncing'

- script: |
    echo All Flutter builds and tests are completed.
  displayName: 'Final Step'
