trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Flutter...
    cd Frontend/user/appUser
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Installing dependencies...
    cd Frontend/user/appUser
    flutter pub get
  displayName: 'Install Flutter dependencies'

- script: |
    echo Building Flutter app for the web...
    cd Frontend/user/appUser
    flutter build web
  displayName: 'Build Flutter app for the web'

- script: |
    echo Running Flutter app...
    cd Frontend/user/appUser
    flutter run
  displayName: 'Run Flutter app as web server'
