trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Flutter...
    cd ecommerce-boutique/Frontend/user/appUser
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Installing dependencies...
    flutter clean
    flutter pub get
  displayName: 'Install Flutter dependencies'

- script: |
    echo Building Flutter app...
    flutter build web --release
  displayName: 'Build Flutter app'

- script: |
    echo Running Flutter app...
    flutter run -d web-server
  displayName: 'Run Flutter app'
  continueOnError: true

- checkout: none
  displayName: 'Disable further repository syncing'

- script: |
    echo All frontend builds and tests are completed.
  displayName: 'Final Step'
