trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo Installing Flutter...
    sudo snap install flutter --classic
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    echo Checking for pubspec.yaml...
    if [ ! -f pubspec.yaml ]; then
      $(which flutter) create .
    fi
  displayName: 'Check and create pubspec.yaml'

- script: |
    echo Installing dependencies...
    $(which flutter) pub get
  displayName: 'Install Flutter dependencies'

- script: |
    echo Running Flutter app...
    flutter run -d web-server
  displayName: 'Run Flutter app'
  continueOnError: true

- checkout: none
  displayName: 'Disable further repository syncing'

- script: |
    echo All frontend builds and tests are completed.
  displayName: 'Final Step'
